Repository COSC481W-2021Fall/capstone-snack-attack, pull requests merged in 2021-12, with the labels that each got.

#76 impl: Implement Place Order Function
  backend/api/order.controller.js
  backend/api/shop.route.js
  backend/dao/orderDAO.js
  backend/index.js
  frontend/src/screens/PlaceOrderScreen.js
  frontend/src/services/cartAction.js
  frontend/src/services/checkoutAction.js
Labels: enhancement, MongoDB, Sprint#4

#79 impl: Add Displaying Products list and Modifying Products information
  backend/api/product.controller.js
  backend/api/shop.route.js
  backend/dao/productDAO.js
  frontend/src/App.js
  frontend/src/bootstrap.min.css
  frontend/src/components/AddProduct.js
  frontend/src/components/header/header.js
  frontend/src/screens/AdminProductListScreen.js
  frontend/src/screens/CartScreen.js
  frontend/src/screens/ProductEditScreen.js
  frontend/src/screens/ProductListScreen.js
  frontend/src/screens/ProductScreen.js
  frontend/src/services/userAction.js
Labels: enhancement, Sprint#4

#80 fix: Fix Logout Automatically When Place Order
  frontend/src/screens/PlaceOrderScreen.js
Labels: bug, testing, Sprint#4

#78 impl: Store Manager Order History Page
  backend/api/order.controller.js
  backend/api/shop.route.js
  backend/dao/orderDAO.js
  frontend/src/App.js
  frontend/src/components/header/header.js
  frontend/src/screens/StoreOrdersScreen.js
  frontend/src/services/userAction.js
Labels: enhancement, Sprint#4

#77 impl: Customer Order History Page
  frontend/package-lock.json
  frontend/src/App.js
  frontend/src/actions/productActions.js
  frontend/src/components/AdminRoute.js
  frontend/src/components/header/header.js
  frontend/src/constants/productConstants.js
  frontend/src/reducers/productReducers.js
  frontend/src/screens/OrderListScreen.js
  frontend/src/services/orderAction.js
  frontend/src/store.js
Labels: enhancement, Sprint#4
