Repository COSC481W-2021Fall/capstone-snack-attack, pull requests merged in 2021-11, with the labels that each got.

#62 impl: Implement Add Product to Cart Function
  backend/api/product.controller.js
  backend/api/shop.route.js
  backend/dao/productDAO.js
  frontend/src/App.js
  frontend/src/components/header/header.js
  frontend/src/constants/cartConstants.js
  frontend/src/reducers/cartReducers.js
  frontend/src/screens/CartScreen.js
  frontend/src/screens/ProductScreen.js
  frontend/src/services/cartAction.js
  frontend/src/services/productAction.js
  frontend/src/store.js
  package-lock.json
  package.json
Labels: enhancement, Sprint#3

#63 impl: Add Buttons to Change Quantity and Remove Item on Cart Page
  frontend/public/uploads/item_2021 Apple MacBook Pro (14-inch, Apple M1 Pro chip with 10‑core CPU and 16‑core GPU, 16GB RAM, 1TB SSD) - Silver_adminID_6179d1d076ff8622057155b7.jpg
  frontend/public/uploads/item_Large Toddler Bookshelf_adminID_6179d1d076ff8622057155b7.jpg
  frontend/public/uploads/item_Llama Llama Misses Mama Board book – Illustrated, September 24, 2019_adminID_6179d1d076ff8622057155b7.jpg
  frontend/public/uploads/item_Melissa & Doug Wooden Train Cars (8 pcs)_adminID_6179d1d076ff8622057155b7.jpg
  frontend/public/uploads/item_Pop Its Rainbow Pop Fidget Toys_adminID_6179d1d076ff8622057155b7.jpg
  frontend/src/constants/cartConstants.js
  frontend/src/reducers/cartReducers.js
  frontend/src/screens/CartScreen.js
  frontend/src/services/cartAction.js
Labels: enhancement, Sprint#3

#67 impl: Display Total Price for Every Item in the Cart
  frontend/src/screens/CartScreen.js
Labels: enhancement, Sprint#3

#66 impl: Add Shipping Address
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/bootstrap.min.css
  frontend/src/components/FormContainer.js
  frontend/src/constants/cartConstants.js
  frontend/src/reducers/cartReducers.js
  frontend/src/screens/CartScreen.js
  frontend/src/screens/PaymentScreen.js
  frontend/src/screens/ShippingAddressScreen.js
  frontend/src/services/cartAction.js
  frontend/src/store.js
Labels: enhancement, Sprint#3

#68 fix: Fix Total Price in Cart
  frontend/src/screens/CartScreen.js
Labels: bug, testing, Sprint#3

#75 impl: Add Payment Method
  backend/api/payment.controller.js
  backend/server.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/components/paymentForm.js
  frontend/src/screens/PaymentScreen.js
  frontend/src/screens/PlaceOrderScreen.js
  frontend/src/screens/ShippingAddressScreen.js
  frontend/src/services/checkoutAction.js
  package-lock.json
  package.json
Labels: enhancement, Sprint#4
