Repository COSC481W-2021Fall/capstone-snack-attack, pull requests merged in 2021-09, with the labels that each got.

#13 Add Pull Request Guidelines
  README.md
Labels: documentation

#14 Fixed Markdown Formatting
  README.md
Labels: documentation

#15 Add the code review checklist first version
  README.md
Labels: help wanted

#17 docs: Add .gitignore file
  .gitignore
Labels: documentation

#21 impl:Setup The Project Structure
  backend/api/.gitkeep
  backend/dao/.gitkeep
  backend/package-lock.json
  backend/package.json
  frontend/.gitignore
  frontend/README.md
  frontend/components/.gitkeep
  frontend/package-lock.json
  frontend/package.json
  frontend/public/favicon.ico
  frontend/public/index.html
  frontend/public/logo192.png
  frontend/public/logo512.png
  frontend/public/manifest.json
  frontend/public/robots.txt
  frontend/services/.gitkeep
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/App.test.js
  frontend/src/index.css
  frontend/src/index.js
  frontend/src/logo.svg
  frontend/src/reportWebVitals.js
  frontend/src/setupTests.js
Labels: enhancement

#18 docs: Add INSTALL Document
  INSTALL.md
Labels: documentation
